services:
  - docker

branches:
  only:
    - master
    - develop
    - /^rc-.+$/

env:
  global:
    - GIZMO_BASE_DOCKER_IMAGE="mayfieldrobotics/gizmo_base"
  matrix:
    - ARCH=x86

notifications:
  email:
    recipients:
      - dev@mayfieldrobotics.com
    on_success: change #[always|never|change] # default: change
    on_failure: change #[always|never|change] # default: always

install:
  - $DOCKER_READONLY

script:
  - |
    repo=$(echo $TRAVIS_REPO_SLUG | cut -d/ -f2)
    if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
      docker run --rm \
        -v ${SSH_AUTH_SOCK}:/ssh-agent \
        -e SSH_AUTH_SOCK=/ssh-agent \
        -v ${TRAVIS_BUILD_DIR}:/root/${repo} \
        ${GIZMO_BASE_DOCKER_IMAGE}:${TRAVIS_BRANCH} \
        sh -c "mkdir -pm 700 ~/.ssh && \
               ssh-keyscan github.com >> ~/.ssh/known_hosts && \
               git clone git@github.com:mayfieldrobotics/embedded-ansible && \
               cd embedded-ansible/deb-build && \
               ./build.py \
                  -r /root/${repo} \
                  -a ${TRAVIS_BRANCH} \
                  -s develop ${CATKIN_IGNORE} ${repo}"
    else
      docker run --rm \
        -v $TRAVIS_BUILD_DIR:/root/$repo \
        ros:indigo \
        sh -ce "
          apt-get update
          apt-get install -y build-essential ros-indigo-rospy-tutorials
          mkdir -p /root/ws/src
          ln -s /root/$repo /root/ws/src/
          . /opt/ros/indigo/setup.sh
          cd /root/ws
          catkin_make
          . devel/setup.sh
          nosetests /root/ws/src/pylaunch/pylaunch/test/test_pylaunch.py
        "
    fi
