services:
  - docker

branches:
  only:
    - master
    - develop
    - /^rc-.+$/

env:
  matrix:
    - ARCH=x86

notifications:
  email:
    recipients:
      - dev@mayfieldrobotics.com
    on_success: change #[always|never|change] # default: change
    on_failure: change #[always|never|change] # default: always

script:
  - |
    repo=$(echo $TRAVIS_REPO_SLUG | cut -d/ -f2)
    docker run --rm \
      -v ${TRAVIS_BUILD_DIR}:/root/${repo} \
      ros:indigo \
      sh -ce "
        apt-get update -qq
        apt-get install -yq build-essential ros-indigo-rospy-tutorials
        mkdir -p /root/ws/src
        ln -s /root/${repo} /root/ws/src/
        . /opt/ros/indigo/setup.sh
        cd /root/ws
        catkin_make
        . devel/setup.sh
        nosetests /root/ws/src/pylaunch/pylaunch/test/test_pylaunch.py
      "
