services:
  - docker

branches:
  only:
    - master
    - develop

env:
  matrix:
    - ARCH=arm
    - ARCH=x86

notifications:
  email:
    recipients:
      - dev@mayfieldrobotics.com
    on_success: change #[always|never|change] # default: change
    on_failure: change #[always|never|change] # default: always

install:
  - $DOCKER_READONLY

script:
  - |
    repo=$(echo $TRAVIS_REPO_SLUG | cut -d/ -f2)
    if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
      if [ "$ARCH" = "arm" ]; then
        ssh -o StrictHostKeyChecking=no -A -p 12422 vpn.mayrobo.com \
          docker run --rm -v \$SSH_AUTH_SOCK:/ssh-agent -e SSH_AUTH_SOCK=/ssh-agent mayfieldrobotics/gizmo_base:ros_indigo_arm \
          "sh -c 'mkdir -pm 700 ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts && git clone git@github.com:mayfieldrobotics/embedded-ansible && cd embedded-ansible/deb-build && ./build.py -d maydistro/may.yaml $repo'"
      elif [ "$ARCH" = "x86" ]; then
        docker run --rm -v $SSH_AUTH_SOCK:/ssh-agent -e SSH_AUTH_SOCK=/ssh-agent -v $TRAVIS_BUILD_DIR:/root/$repo \
          mayfieldrobotics/gizmo_base:ros_indigo_x86 \
          sh -c "mkdir -pm 700 ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts && git clone git@github.com:mayfieldrobotics/embedded-ansible && cd embedded-ansible/deb-build && ./build.py -d maydistro/may.yaml -r /root/$repo $repo"
      fi
    else
      if [ "$ARCH" = "x86" ]; then
        docker run --rm \
          -v $TRAVIS_BUILD_DIR:/root/$repo \
          ros:indigo \
          sh -ce "
            apt-get update
            apt-get install -y build-essential ros-indigo-rospy-tutorials
            mkdir -p /root/ws/src
            ln -s /root/$repo /root/ws/src/
            . /opt/ros/indigo/setup.sh
            cd /root/ws
            catkin_make
            . devel/setup.sh
            nosetests /root/ws/src/pylaunch/pylaunch/test/test_pylaunch.py
          "
      fi
    fi
